[files]
input_file = '..\Moscow_17.02.2025\beltpack_roaming_izm_1.log'
output_file = '..\result\temp_result_roaming_izm_1.log'
recon_objs  = '..\result\recon_objs.obj'

[options]
Option_0 = 90
Option_1 = 90
Option_2 = 32
Option_3 = 65
Option_4 = 5
Option_5 = 5
Option_6 = 5
Option_7 = 5
Option_8 = 150
Option_9 = 150
Option_10 = 150
Option_11 = 15
Option_12 = 9
Option_13 = 163
Option_14 = 2
Option_15 = 10
Option_16 = 5
Option_17 = 150
Option_18 = 172
Option_19 = 60